import Foundation
import Metal
import Testing

import SploshCore
import SploshOracle

@Suite("M23cSwigluTests")
struct M23cSwigluTests {
    private struct Params {
        var length: UInt32
    }

    private let gateBits: [UInt16] = [
        0x0000, 0x3f80, 0xbf80, 0x4120, 0xc120, 0x3eaa, 0x4265, 0xc2c8
    ]
    private let upBits: [UInt16] = [
        0x3f80, 0x4000, 0x4040, 0xbf00, 0x4120, 0xc000, 0x3e80, 0x42a0
    ]

    @Test("SwigluOracle.gate uses SiLU times up")
    func oracleMatchesIndependentVector() {
        let result = SwigluOracle.gate(gate: gateBits, up: upBits)
        // The first four values are independently recorded bf16 outputs from the
        // reference definition, not generated by the engine under test.
        #expect(result.prefix(4).elementsEqual([0x0000, 0x3fbb, 0xbf4f, 0xc0a0]))
        #expect(result.count == gateBits.count)
    }

    @Test("swiglu shader agrees with the CPU oracle within bf16 tolerance")
    func shaderRelErr() throws {
        guard let device = MTLCreateSystemDefaultDevice() else {
            throw SploshError.capabilityGateFailure("no Metal device on this host")
        }
        let metallib = try makeTestMetallib(device: device)
        let pipeline = try metallib.pipeline("swiglu")
        let n = gateBits.count
        let length = n * MemoryLayout<UInt16>.stride
        guard let gate = device.makeBuffer(bytes: gateBits, length: length, options: .storageModeShared),
              let up = device.makeBuffer(bytes: upBits, length: length, options: .storageModeShared),
              let output = device.makeBuffer(length: length, options: .storageModeShared),
              let queue = device.makeCommandQueue(),
              let command = queue.makeCommandBuffer(),
              let encoder = command.makeComputeCommandEncoder() else {
            throw SploshError.capabilityGateFailure("could not allocate SwiGLU Metal resources")
        }
        var params = Params(length: UInt32(n))
        encoder.setComputePipelineState(pipeline)
        encoder.setBuffer(gate, offset: 0, index: 0)
        encoder.setBuffer(up, offset: 0, index: 1)
        encoder.setBuffer(output, offset: 0, index: 2)
        encoder.setBytes(&params, length: MemoryLayout<Params>.size, index: 3)
        encoder.dispatchThreads(MTLSize(width: n, height: 1, depth: 1),
                                threadsPerThreadgroup: MTLSize(width: min(n, pipeline.maxTotalThreadsPerThreadgroup), height: 1, depth: 1))
        encoder.endEncoding()
        command.commit()
        command.waitUntilCompleted()
        if let error = command.error { throw SploshError.capabilityGateFailure("swiglu command failed: \(error)") }

        let observed = output.contents().bindMemory(to: UInt16.self, capacity: n)
        let expected = SwigluOracle.gate(gate: gateBits, up: upBits)
        var numerator: Double = 0
        var denominator: Double = 0
        for i in 0..<n {
            let actual = Float(bitPattern: UInt32(observed[i]) << 16)
            let reference = Float(bitPattern: UInt32(expected[i]) << 16)
            numerator += Double(abs(actual - reference))
            denominator += Double(max(abs(reference), 1e-6))
        }
        let relErr = numerator / denominator
        print("SwigluOracle.gate relErr=\(relErr) tolerance=1e-2")
        #expect(relErr <= 1e-2, "relErr=\(relErr) exceeds bf16 tolerance 1e-2")
    }

    @Test("metallib exports exactly the M2.3c set")
    func exactExportSet() throws {
        let device = try #require(MTLCreateSystemDefaultDevice())
        let metallib = try makeTestMetallib(device: device)
        #expect(Set(metallib.functionNames) == ["copy", "rmsnorm", "rope_mrope", "swiglu"])
    }
}
